### ISSUE TITLE
🐞 [BUG] - icon can not overlap subscribe 

### ISSUE THREAD

**Issue by kapilG0** [anmode/Move-to-nextJS#875] opened 2024-10-07 09:03 UTC
### Description

Icons are overlapping on subscribe 

### Current behaviour

![Screenshot_20241007_143111](https://github.com/user-attachments/assets/2d6bdfe2-769a-4a5d-8ae6-36463d667554)

### Expected behaviour

Icon should not overlap 

### Reproduction steps

```bash
Go to home page and scroll below to configure that
```

### Screenshots

![DESCRIPTION](LINK.png)

### Browsers

Chrome

### Are you contributing for a program ?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Sanchitbajaj02** [comment] 2024-10-08 08:37
Hi @kapilG0 
Can you explain how you are going to fix this issue as placing the support icon somewhere else will not look good?

**Comment by coderKrysio** [comment] 2024-10-09 05:15
hi @Sanchitbajaj02 
as you can see the opacity of the chat button is low and its not perfectly aligned with scroll-to-top button
![image](https://github.com/user-attachments/assets/6a1f5546-1b1a-4d25-83b5-d10f90a7c518)

so here is the proposed solution:
1. we increase the chat button opacity 
2. we align it with scroll-to-top button so that it doesnt look improper 
3. we change the color of the chat button to a darker shade from the website's proposed brand color palette

if you find these changes well and good, please assign me this issue

**Comment by Sanchitbajaj02** [comment] 2024-10-10 05:32
Hi @coderKrysio 
I like the idea of your proposal.

Since @kapilG0 didn't respond yet, I am assigning this issue to you

**Comment by coderKrysio** [comment] 2024-10-10 05:34
Thank you @Sanchitbajaj02 
And can you add the level 2 label to this issue, it would be of great help

**Comment by Sanchitbajaj02** [comment] 2024-10-10 05:36
> Thank you @Sanchitbajaj02 And can you add the level 2 label to this issue, it would be of great help

I feel that the change is not major that it needs to be level 2. @anmode what's your opinion on this?

**Comment by coderKrysio** [comment] 2024-10-10 11:56
hey @Sanchitbajaj02 
i have forked the repo and was installing the deps but got this issue
![image](https://github.com/user-attachments/assets/32cf03d1-c7de-4c96-8112-cf00cba67658)

even after using the command npm run dev
I am unable to save any new changes and view it
the site is working fine after running this command, but it is not accepting any new changes and is making formatting error
can you help me with this

**Comment by Sanchitbajaj02** [comment] 2024-10-10 17:18
Hi @coderKrysio 
can you check and tell me what is your node and npm version installed? Because this isn't the major error, just the dependency issue which will gets fixed by using the latest version

**Comment by coderKrysio** [comment] 2024-10-10 17:22
@Sanchitbajaj02 
![image](https://github.com/user-attachments/assets/3348a46c-15cf-40d7-bba3-abab450ad2fe)

Is the formatting issue caused by Eslint and Prettier being used together?
because even after dependency installation, I am unable to save any file properly

**Comment by coderKrysio** [comment] 2024-10-11 05:52
hey @Sanchitbajaj02 
can you help me?
the formatting issue is still not resolved
I want to fix this error as soon as possible

**Comment by coderKrysio** [comment] 2024-10-11 09:08
hey @Sanchitbajaj02 
please take a look at this error

https://github.com/user-attachments/assets/3cd30d17-d74e-4015-9735-42e5aac3fc75

and let me know the measures I can take to fix it

**Comment by Sanchitbajaj02** [comment] 2024-10-11 09:21
> hey @Sanchitbajaj02 please take a look at this error
> 
>  Untitled.video.-.Made.with.Clipchamp.mp4 
> and let me know the measures I can take to fix it

For this, you can open your VS Code settings and disable the format on save feature

**Comment by Sanchitbajaj02** [comment] 2024-10-11 09:22
> @Sanchitbajaj02 ![image](https://private-user-images.githubusercontent.com/91840205/375481254-3348a46c-15cf-40d7-bba3-abab450ad2fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2Mzg3NjIsIm5iZiI6MTcyODYzODQ2MiwicGF0aCI6Ii85MTg0MDIwNS8zNzU0ODEyNTQtMzM0OGE0NmMtMTVjZi00MGQ3LWJiYTMtYWJhYjQ1MGFkMmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA5MjEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMmIxOTI2ZDFlZDA3MDMxYWNiMjUwZmViNDRjMjA0ODM3OTkxYzU0MzM4NGJmZTRjYTFjZmRlNzU5NDY5YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iNpcXSLl7T5fYQ4NwrCrMDyQFDZmP_4ztVobwU9PVkE)
> 
> Is the formatting issue caused by Eslint and Prettier being used together? because even after dependency installation, I am unable to save any file properly

Yeah, seems like it, you can follow the above mentioned step to fix the issue

**Comment by coderKrysio** [comment] 2024-10-11 09:24
> > hey @Sanchitbajaj02 please take a look at this error
> > Untitled.video.-.Made.with.Clipchamp.mp4
> > and let me know the measures I can take to fix it
> 
> For this, you can open your VS Code settings and disable the format on save feature

I already did but still facing the same error

**Comment by Sanchitbajaj02** [comment] 2024-10-11 09:26
Have you tried the auto save functionality? I think that does not do formatting

**Comment by coderKrysio** [comment] 2024-10-11 09:27
> Have you tried the auto save functionality? I think that does not do formatting

tried that right now and still facing the same error

**Comment by Sanchitbajaj02** [comment] 2024-10-11 09:28
> > Have you tried the auto save functionality? I think that does not do formatting
> 
> tried that right now and still facing the same error

is it possible that you can show me over discord?

**Comment by coderKrysio** [comment] 2024-10-11 09:29
> > > Have you tried the auto save functionality? I think that does not do formatting
> > 
> > 
> > tried that right now and still facing the same error
> 
> is it possible that you can show me over discord?

yeah sure we can discuss this on video call

**Comment by Sanchitbajaj02** [comment] 2024-10-11 09:31
> > > > Have you tried the auto save functionality? I think that does not do formatting
> > > 
> > > 
> > > tried that right now and still facing the same error
> > 
> > 
> > is it possible that you can show me over discord?
> 
> yeah sure we can discuss this on video call

Please join the doubts voice channel on gssoc server and show me the issue

**Comment by coderKrysio** [comment] 2024-10-11 09:33
> > > > > Have you tried the auto save functionality? I think that does not do formatting
> > > > 
> > > > 
> > > > tried that right now and still facing the same error
> > > 
> > > 
> > > is it possible that you can show me over discord?
> > 
> > 
> > yeah sure we can discuss this on video call
> 
> Please join the doubts voice channel on gssoc server and show me the issue

I have opened one with the name anushree | contributor

**Comment by coderKrysio** [comment] 2024-10-11 12:33
Hey @Sanchitbajaj02 
made the changes, need your confirmation before creating a pr
https://github.com/user-attachments/assets/d379e6b9-311c-46b8-8f65-e48e0a6618e9

**Closed as completed** 2024-10-12 07:19 UTC
Labels: bug, level1, hacktoberfest, hacktoberfest-accepted, gssoc-ext
