### ISSUE TITLE
BackToTop Button Scrolling Issue

### ISSUE THREAD

**Issue by Shariq2003** [anmode/Move-to-nextJS#854] opened 2024-10-04 21:30 UTC
On observing, I have found that the backtotop button working is not smooth, making a bad experience for user.

https://github.com/user-attachments/assets/7e4071b3-ab6f-407c-9fc5-583725a2c92f

@anmode Please assign this to me.

**Comment by Sanchitbajaj02** [comment] 2024-10-06 17:24
Hi @Shariq2003 
It looks like the scroll to top is just snapping to top without any smooth animation. I am assigning this issue to you, but can you please give a brief, how you are going to fix this issue?

**Comment by Shariq2003** [comment] 2024-10-06 17:30
> Hi @Shariq2003 It looks like the scroll to top is just snapping to top without any smooth animation. I am assigning this issue to you, but can you please give a brief, how you are going to fix this issue?

By adjusting the default scroll behavior of the window,
adjusting the speed based on the Y axis

**Comment by Shariq2003** [comment] 2024-10-06 20:22
@Sanchitbajaj02 please review my PR, and could u please add level 2 as this a fix that should be of level 2

Level 1: Documentation
Level 2: Fixes
Level 3: New Feature

**Closed as completed** 2024-10-10 17:16 UTC
Labels: level1, hacktoberfest, hacktoberfest-accepted, gssoc-ext

**Comment by coderKrysio** [comment] 2024-10-11 07:30
hey @Shariq2003 
I am working on another issue right now and I am unable to setup the repo properly
I have contacted the collaborators but have not gotten any response
can you please help me out with the setup process that you have done to contribute to this successfully

**Comment by Shariq2003** [comment] 2024-10-11 08:47
> hey @Shariq2003 I am working on another issue right now and I am unable to setup the repo properly I have contacted the collaborators but have not gotten any response can you please help me out with the setup process that you have done to contribute to this successfully

@coderKrysio follow the readme instructions

**Comment by coderKrysio** [comment] 2024-10-11 08:49
> > hey @Shariq2003 I am working on another issue right now and I am unable to setup the repo properly I have contacted the collaborators but have not gotten any response can you please help me out with the setup process that you have done to contribute to this successfully
> 
> @coderKrysio follow the readme instructions

I did, but I am facing some formatting issue while saving any new changes
did you faced the same?

**Comment by Shariq2003** [comment] 2024-10-11 08:51
> > > hey @Shariq2003 I am working on another issue right now and I am unable to setup the repo properly I have contacted the collaborators but have not gotten any response can you please help me out with the setup process that you have done to contribute to this successfully
> > 
> > 
> > @coderKrysio follow the readme instructions
> 
> I did, but I am facing some formatting issue while saving any new changes did you faced the same?

No, I have not faced any such issues.

**Comment by Shariq2003** [comment] 2024-10-11 08:52
> > > hey @Shariq2003 I am working on another issue right now and I am unable to setup the repo properly I have contacted the collaborators but have not gotten any response can you please help me out with the setup process that you have done to contribute to this successfully
> > 
> > 
> > @coderKrysio follow the readme instructions
> 
> I did, but I am facing some formatting issue while saving any new changes did you faced the same?

What kind of formating issues ?

**Comment by coderKrysio** [comment] 2024-10-11 08:55
> > > > hey @Shariq2003 I am working on another issue right now and I am unable to setup the repo properly I have contacted the collaborators but have not gotten any response can you please help me out with the setup process that you have done to contribute to this successfully
> > > 
> > > 
> > > @coderKrysio follow the readme instructions
> > 
> > 
> > I did, but I am facing some formatting issue while saving any new changes did you faced the same?
> 
> What kind of formating issues ?

the installation process and deploying on local is working fine
but whenever I am making a new change and saving the file, the file complies into wrong formatting style

I have an automatic format of prettier set in vs code, it never raises any issue
but in this repo eslint and prettier are together, can that be the cause?

**Comment by Shariq2003** [comment] 2024-10-11 09:03
> > > > > hey @Shariq2003 I am working on another issue right now and I am unable to setup the repo properly I have contacted the collaborators but have not gotten any response can you please help me out with the setup process that you have done to contribute to this successfully
> > > > 
> > > > 
> > > > @coderKrysio follow the readme instructions
> > > 
> > > 
> > > I did, but I am facing some formatting issue while saving any new changes did you faced the same?
> > 
> > 
> > What kind of formating issues ?
> 
> the installation process and deploying on local is working fine but whenever I am making a new change and saving the file, the file complies into wrong formatting style
> 
> I have an automatic format of prettier set in vs code, it never raises any issue but in this repo eslint and prettier are together, can that be the cause?

well, I have also worked on this repo, and have not faced any such issues,
